### ISSUE TITLE
Custom matcha generation not working correctly

### ISSUE THREAD

**Issue by tekstrand** [lowlighter/matcha#16]
I've noticed a few issues
- Colors not working correctly. Seems that dark/light colors are mixed up and i end up with dark text or dark bg or invisible text altogether
- font families missing

**Comment by lowlighter** [comment]
Hi !

I'll look into providing a more robust builder, it's true that for variables customization it's currently a bit wacky.
I'll also look to let users customize properties other than colors

**Comment by GarrettAlbright** [comment]
I can confirm that a whole bunch of variables are missing. I think the entire @root.css file is not being included. If it helps here's a screenshot of the options I'm trying to use (I don't need syntax highlighting or code editing features and altering anything about the look and behavior of scrollbars is a crime against of humanity worthy of trial in the Hague).

<img width="843" alt="matcha" src="https://github.com/lowlighter/matcha/assets/324483/c206158f-41f1-473e-8c11-09c46dac7b41">
