### ISSUE TITLE
[Bug] Nav Menu does not work properly on mobile

### ISSUE THREAD

**Issue by tekstrand** [lowlighter/matcha#18]
Items that are too long overflow and aren't positioned properly
<img width="502" alt="Screenshot 2024-06-01 at 6 48 31 PM" src="https://github.com/lowlighter/matcha/assets/5215365/a40ebc38-1591-48bb-8e30-2a19b322dd65">

**Comment by lowlighter** [comment]
I think we could fix this by switching to `flex-direction: column` on small screen, with menu elements taking the whole width
