### ISSUE TITLE
Demo site: color scheme-based styles are not applied by default

### ISSUE THREAD

**Issue by tetradice** [lowlighter/matcha#34]
When you view the matcha.css demo site in Google Chrome or Firefox on Windows, color scheme-based styles are not applied by default.

As a result, the screen looks bland, unlike the screen capture on GitHub.

![image](https://github.com/lowlighter/matcha/assets/802975/5bff99c8-5928-4fbc-91c2-fd6d9e234c28)

If I press the button in the top right of the screen once, the color scheme-based styles are applied,

![image](https://github.com/lowlighter/matcha/assets/802975/a97c0e4a-6137-45d1-81b7-40c244547461)

I don't know if this is intentional, but I thought it might be unintentional, so I reported it.

I apologize if this is an intentional specification.

### Environment

OS: Windows 11
Browser: Google Chrome 125.0.6422.144 (x64) / FireFox 125.0.1 (x64)

*I have never changed the color scheme settings in my browser or OS settings. I have not specified either the light or dark theme.

**Comment by andremantaswow** [comment]
Same here, i noticed this locally while trying the styles. It basically means I can't see any inputs if they dont have placeholders

![image](https://github.com/lowlighter/matcha/assets/58601723/2a5442b9-d9df-4e2a-a62d-f1ceed8147c8)

After clicking on the input:
![image](https://github.com/lowlighter/matcha/assets/58601723/6f6ab5c6-05d2-435d-9722-dfb708b9e10c)

Code
```html
<!DOCTYPE html>
<html>

<head>
    <title>Data Fetcher</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://matcha.mizu.sh/matcha.css">
</head>

<body>
    <h1>Data Fetcher</h1>
    <form>
        <label for="token">Token:
            <input type="text" id="token" name="token" required>
        </label>

        <label for="name">Name:
            <input type="text" id="name" name="name" required>
        </label>
        <button type="submit">Fetch Data</button>
    </form>

    <div id="resultContainer">
    </div>
</body>

</html>
```

**Comment by hasinhayder** [comment]
A quick solution is to add data-color-scheme="light" or data-color-scheme="dark" to the <body> element, or the parent div

like ```<body data-color-scheme="light"``` or ```<div data-color-scheme="light"```


matcha team should fix it

**Comment by lowlighter** [comment]
Hi ! 
This should be fixed now, didn't catch it because it seemed to only affect light mode system users
Let me know if you still have issues ! Thanks for reporting this issue !
