### ISSUE TITLE
Checkboxes can be confused for radio buttons

### ISSUE THREAD

**Issue by spartanatreyu** [lowlighter/matcha#5]
Checkboxes currently show their checked status by drawing a black check over a dark-blue rounded box.

Screenshot:
<img width="152" alt="current checkbox example" src="https://github.com/lowlighter/matcha/assets/3240456/9a5421ee-5242-482d-a4bf-d627a972c59d">

For users with poor vision, it's too easy for the checkboxes to be confused with radio buttons which will lead users to incorrectly assume that they can only select one of the possible options at the time.

Simulated screenshot with a 4px gaussian blur:

<img width="152" alt="current checkbox example blurred" src="https://github.com/lowlighter/matcha/assets/3240456/8de1f58e-917b-4f90-b1d5-2110c3fc22a8">

---

Proposed Solution:

1. Remove border-radius to distinguish checkbox from radio button.
2. Change stroke color to white

Proposed change screenshot:

<img width="136" alt="proposed checkbox example" src="https://github.com/lowlighter/matcha/assets/3240456/21c49279-7685-4a9d-ac7b-eb992b244dbe">

Proposed change simulated screenshot with a 4px gaussian blur:

<img width="136" alt="proposed checkbox example blurred" src="https://github.com/lowlighter/matcha/assets/3240456/8230f029-f181-402b-a417-2c235d916037">

**Comment by lowlighter** [comment]
Hi !
Thanks for reporting this, indeed I can see why this can be confused

The stroke is supposed to be white, but I think it's probably caused because it inherits the default color font which is white for dark mode, but black in light mode. Will look into a patch

**Comment by spartanatreyu** [comment]
A white stroke in both light and dark modes is probably going to be the best.
